### PR TITLE
Add a simple test

### PR DESCRIPTION
**Pull request by andrewshadura**
Add tests for issues found in #1, #3, #7.

### CODE REVIEW

**Comment by andrewshadura** [comment]
Found some issues with this 🙂 Turns out busybox nslookup behaves differently enough to cause issues.

**Comment by andrewshadura** [comment]
cc @Leseratte10

**Comment by andrewshadura** [comment]
Okay, I’m going to merge this since there were no objections so far 😃

**Comment by Leseratte10** [comment]
Whoops, missed that mention somehow. Yeah, couldn't hurt to have a couple small tests that test A) some core functionality and B) edge cases to make sure they don't get broken again in the future.

**Comment by Leseratte10** [comment]
What is the "correct" way to run these tests?

When I try `./configure`, `make`, `make distcheck` there's errors when running the tests: 

```
...
...
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -Wall -MT parser.lo -MD -MP -MF .deps/parser.Tpo -c -o parser.lo ../../parser.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -g -O2 -Wall -MT parser.lo -MD -MP -MF .deps/parser.Tpo -c ../../parser.c  -fPIC -DPIC -o .libs/parser.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -g -O2 -Wall -MT parser.lo -MD -MP -MF .deps/parser.Tpo -c ../../parser.c -o parser.o >/dev/null 2>&1
mv -f .deps/parser.Tpo .deps/parser.Plo
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wc,-nostdlib  -o libtnat64.la -rpath /lib/tnat64 tnat64.lo common.lo parser.lo -ldl -lc -lc
libtool: link: gcc -shared  -fPIC -DPIC  .libs/tnat64.o .libs/common.o .libs/parser.o   -ldl -lc  -g -O2 -nostdlib   -Wl,-soname -Wl,libtnat64.so.0 -o .libs/libtnat64.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libtnat64.so.0" && ln -s "libtnat64.so.0.0.0" "libtnat64.so.0")
libtool: link: (cd ".libs" && rm -f "libtnat64.so" && ln -s "libtnat64.so.0.0.0" "libtnat64.so")
libtool: link: ar cr .libs/libtnat64.a  tnat64.o common.o parser.o
libtool: link: ranlib .libs/libtnat64.a
libtool: link: ( cd ".libs" && rm -f "libtnat64.la" && ln -s "../libtnat64.la" "libtnat64.la" )
sed -e 's,[@]libdir[@],/lib,g' -e 's,[@]pkglibdir[@],/lib/tnat64,g' -e 's,[@]bindir[@],/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_inst/bin,g' -e 's,[@]CONF_FILE[@],/etc/tnat64.conf,g' -e 's,[@]PERL[@],,g' -e 's,[@]PACKAGE[@],tnat64,g' -e 's,[@]VERSION[@],0.06,g' < ../../tnat64.in > tnat64
chmod +x tnat64
sed -e 's,[@]libdir[@],/lib,g' -e 's,[@]pkglibdir[@],/lib/tnat64,g' -e 's,[@]bindir[@],/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_inst/bin,g' -e 's,[@]CONF_FILE[@],/etc/tnat64.conf,g' -e 's,[@]PERL[@],,g' -e 's,[@]PACKAGE[@],tnat64,g' -e 's,[@]VERSION[@],0.06,g' < ../../tnat64.8.in > tnat64.8
make[2]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[1]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[1]: Entering directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[1]: Nothing to be done for 'dvi'.
make[1]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[1]: Entering directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make  check-TESTS
make[2]: Entering directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[3]: Entering directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[3]: *** No rule to make target 'tests/01-correct-ipv6-address', needed by 'tests/01-correct-ipv6-address.log'.  Stop.
make[3]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[2]: *** [Makefile:1184: check-TESTS] Error 2
make[2]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make[1]: *** [Makefile:1396: check-am] Error 2
make[1]: Leaving directory '/home/florian/tnat64ci/tnat64ci/tnat64-0.06/_build/sub'
make: *** [Makefile:1319: distcheck] Error 1
```


I can run `make test-suite.log` instead, but is that "the intended method"?

**Comment by andrewshadura** [comment]
Huh, I only ever used `make check`.

**Comment by Leseratte10** [comment]
Okay, that's working. This is the first time I'm using a project using automake and Google said to run make distcheck :P
I'm currently trying to bundle that into a Github CI action to auto-run the tests for each commit.

**Comment by andrewshadura** [comment]
Great, thanks! In any case, I also have a mostly working Meson conversion, so eventually we can use that instead.

**Comment by andrewshadura** [comment]
I think the reason `distcheck` didn’t work is that I probably didn’t include the code of the tests into the distribution somehow.

**Pull request merged**
